### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by glatard** [LivingPark-MRI/livingpark-utils#2]
Notebooks need `livingpark_utils` to run `prologue` function but dependencies are installed in prologue function.

**Comment by mathdugre** [comment]
@glatard is this still an issue with the newer version of the package?

**Comment by glatard** [comment]
yes I believe so but I can't think of a way to address it

**Comment by mathdugre** [comment]
The notebook initialization no longer install dependencies (see [here](https://github.com/LivingPark-MRI/livingpark-utils/blob/main/livingpark_utils/livingpark_utils.py#L69)).
The installation is now done externally.
