### ISSUE TITLE
`disease_duration` function

### ISSUE THREAD

**Issue by rmanaem** [LivingPark-MRI/livingpark-utils#57]
Noticed something when using [`disease_duration`](https://github.com/LivingPark-MRI/livingpark-utils/blob/b3d7f7cb19271474ddb47b2c18d4fbb186a072d1/livingpark_utils/dataset/ppmi.py#L36) function in the `ppmi.py` module.
https://github.com/LivingPark-MRI/livingpark-utils/blob/b3d7f7cb19271474ddb47b2c18d4fbb186a072d1/livingpark_utils/dataset/ppmi.py#L67-L71
If my understanding of the above implementation semantics is correct, we'd like the difference between the date in the `INFODT` column and `PDDXDT` column in months. However, it seems the function is simply taking the difference in months while discarding the years. see the example below

![Screenshot from 2023-03-02 15-10-48](https://user-images.githubusercontent.com/77515879/222541342-8b85781d-500b-4623-acc1-22396e6a495c.png)

**Comment by mathdugre** [comment]
#59 fixes this issue.
